name: buildarm
on:
  workflow_dispatch:

jobs:
  aarch64_job:
    runs-on: ubuntu-18.04
    name: build
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: darsvador/run-on-arch-action@v1.0.10
        id: runcmd
        with:
          architecture: aarch64
          distribution: archlinuxarm
          run: |
            echo "container is ready."
            yes $'\n'|pacman -Syu base-devel unzip p7zip busybox rclone git
            useradd -m build
            chown -R build ./*
            echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            mkdir -p ~/.config/rclone/
            touch ~/.config/rclone/rclone.conf
            echo -e '${{secrets.ONEDRIVE_CONFIG}}' >> ~/.config/rclone/rclone.conf
            for pkg in `cat need-update`
              do
                 pwd
                 cd pkgbuild/"${pkg}"/
                 if [ -f "./aur" ];then
                   su -c "git clone https://aur.archlinux.org/${pkg}.git 
                          cd ./${pkg}
                          sh ../aur
                          source PKGBUILD
                          pacman -S $makedepends --noconfirm
                         makepkg -d" build
                   cd ./${pkg}
                  elif [ -f "./PKGBUILD" ];then
                    su -c "source PKGBUILD
                           pacman -S $makedepends --noconfirm
                           makepkg -d" build
                    echo "Build finished"
                  else
                    echo "Skipping:No build files provided."
                  fi
                  mkdir -p /mnt/onedrive
                  if [[ `ls` == *"-aarch64.pkg.tar.zst"* ]];then
                    rclone move one:/arch-repo/aarch64/ one:/arch-archive/  --include "${pkg}-*.pkg.tar.zst"
                    rclone move one:/arch-repo/aarch64/ ./ --exclude "*.tar.zst"
                    repo-add ./coal.db.tar.gz ./*.pkg.tar.zst
                    for p in `ls *.pkg.tar.zst`
                    do
                      rclone move ./${p} one:/arch-repo/aarch64/
                    done
                    for f in `ls coal*`
                    do
                      rclone move ./${f} one:/arch-repo/aarch64/
                    done
                  else
                    echo "Skipping:No packages found."
                  fi
                  echo "Upload finished"
              done
  rm-update:
    runs-on: ubuntu-latest
    needs: aarch64_job
    steps:
      - uses: actions/checkout@v2
      - name: Remove need-update
        run: |
             rm need-update
             git config --local user.email "w1301511091@hotmail.com"
             git config --local user.name "oganesson0512"
             git add .
             git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}