name: buildarm
on:
  workflow_dispatch:

jobs:
  aarch64_job:
    runs-on: ubuntu-18.04
    name: build
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: darsvador/run-on-arch-action@v1.0.10
        id: runcmd
        with:
          architecture: aarch64
          distribution: archlinuxarm
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"